name: Build App

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    name: Create release draft
    steps:
      - name: Git checkout
        uses: actions/checkout@v2.3.4

      - name: Get the tag name
        id: vars
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/*/}
          echo ::set-output name=version::${GITHUB_REF#refs/*/v}

      - name: Create Release
        uses: ncipollo/release-action@v1.8.6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true

  build:
    needs: create-release
    runs-on: windows-latest
    name: Build ${{ matrix.module }}
    strategy:
      matrix:
        module:
          - "windows.foundation"
          - "windows.media"
          - "windows.media.playback"
          - "windows.storage.streams"
    steps:
      - name: Git checkout
        uses: actions/checkout@v2.3.4

      - name: Prepare Node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: "14"
          cache: "npm"

      - name: Get the tag name
        id: vars
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/*/}
          echo ::set-output name=version::${GITHUB_REF#refs/*/v}
        shell: bash

      - name: Set version for ${{ matrix.module }}
        env:
          REN_MODULE: ${{ matrix.module }}
          TAG: ${{ steps.vars.outputs.tag }}
        run: |
          echo "Set version for module: $Env:REN_MODULE"
          echo "Version tag: $Env:TAG"
          cd $Env:REN_MODULE
          npm version $Env:TAG

      - name: Pack module ${{ matrix.module }}
        env:
          REN_MODULE: ${{ matrix.module }}
        run: |
          echo "Pack module: $Env:REN_MODULE"
          $outPath = "out";
          if (!(Test-Path -path $outPath)) {
            New-Item -ItemType directory -Path $outPath
          }
          cd out
          npm pack ..\$Env:REN_MODULE

      - name: Create Release
        uses: ncipollo/release-action@v1.8.6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: out/${{ matrix.module }}-${{ steps.vars.outputs.version }}.tgz
          artifactContentType: application/gzip
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          replacesArtifacts: false
          draft: false
